# hosts.yml
---
all:                        # ← το root group (πάντα "all")
  hosts:                    # ← απευθείας hosts στο "all"
    myserver:
      ansible_host: 192.168.1.10

  children:                 # ← child groups του "all"
    webservers:             # ← ένα group
      hosts:                # ← hosts αυτού του group
        web01:
          ansible_host: 192.168.1.11
        web02:
          ansible_host: 192.168.1.12

    dbservers:              # ← άλλο group
      hosts:
        db01:
          ansible_host: 192.168.1.20
